### ISSUE TITLE
Cloudinary Image component: Can't perform React state update

### ISSUE THREAD

**Issue by Rowan-Paul** [Rowan-Paul/GWENTcards#22]
When signing in or out, React gives the following error message:
```
vendors~main.chunk.js:51706 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at Image (http://localhost:3001/static/js/vendors~main.chunk.js:12258:34)
    at section
    at div
    at span
    at CardUI (http://localhost:3001/static/js/main.chunk.js:270:107)
    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:55619:75)
```

This seems to come from the `Image` tag from the `cloudinary-react` library, specifically the `loading="lazy"` attribute. When that attribute is removed, there is no error message. I can't find anything on Google about it so it's probably not related to the cloudinary package, but who knows.

The following logfile is what I got inside my console log after logging in: [localhost-1621865307797.log](https://github.com/Rowan-Paul/GWENTcards/files/6532945/localhost-1621865307797.log)

**Comment by Rowan-Paul** [comment]
At the current commit 9d1e8de97ebe010fd682d0158f2aff391062eb71 this doesn't seem to happen anymore, so I'm closing this issue (how was it fixed? no idea)
